include ../../global_config

OBJS = \
	$(OBJDIR)/downsample.o \
	$(OBJDIR)/downsampleengine.o

OUTPUT = ../$(OBJDIR)/downsample.plugin

include ../../plugin_config

$(OBJDIR)/downsample.o: downsample.C
$(OBJDIR)/downsampleengine.o: downsampleengine.C
